/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class umeng_x_con_umengtest_JniTest */

#ifndef _Included_umeng_x_con_umengtest_JniTest
#define _Included_umeng_x_con_umengtest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     umeng_x_con_umengtest_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_umeng_x_con_umengtest_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     umeng_x_con_umengtest_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_umeng_x_con_umengtest_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
